/**
 * Generated by Aster
 */
package com.ibm.websphere.samples.daytrader.web.jsf;

import java.util.concurrent.TimeUnit;
import javax.faces.validator.ValidatorException;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Timeout;
import org.junit.jupiter.api.Timeout.ThreadMode;

import static org.junit.jupiter.api.Assertions.fail;
import static org.junit.jupiter.api.Timeout.ThreadMode.SEPARATE_THREAD;

public class Aster_LoginValidator_Coverage_Test_Passing {
    @Test
    @Timeout(value = 1, unit = TimeUnit.SECONDS, threadMode = SEPARATE_THREAD)
    public void testValidate1_ERfV0() throws javax.faces.validator.ValidatorException {
        LoginValidator loginValidator = new LoginValidator();
        String value = "uid:123456789";
        try {
            loginValidator.validate(null, null, value);
        } catch (ValidatorException e) {
            fail("Unexpected exception thrown: " + e.getMessage());
        }
    }
}